Repository nekoyume/nekoyume, pull requests merged in 2018-10, with the labels that each got.

#132 Introduce .editorconfig
  .editorconfig
  app.json
Labels: bug, utility

#131 Add flake8 excludes to setup.cfg
  setup.cfg
Labels: good first issue

#130 Refactor battle logger
  nekoyume/battle/__main__.py
  nekoyume/battle/characters.py
  nekoyume/battle/components/bag.py
  nekoyume/battle/components/behaviors/__init__.py
  nekoyume/battle/components/behaviors/skills/__init__.py
  nekoyume/battle/components/stats.py
  nekoyume/battle/logger.py
  nekoyume/battle/simul.py
  nekoyume/battle/status/__init__.py
  nekoyume/battle/status/base.py
  nekoyume/battle/status/item.py
  nekoyume/battle/status/skills.py
  nekoyume/battle/status/spawn.py
  nekoyume/battle/status/stats.py
  nekoyume/battle/status/zone.py
  nekoyume/models.py
  nekoyume/tables/monster_appear.tsv
  nekoyume/tables/skills.tsv
  nekoyume/templates/dashboard.html
Labels: enhancement
